### ISSUE TITLE
Docs: Inspiration

### ISSUE THREAD

**Issue by DrewBradley** [dietza/FitLit#1]
As a developer, I want to have a clean and user-friendly layout,

When I design my application,

I want to emphasize usability and enjoyment for a user,

By pulling inspiration from other fitness applications, utilizing wireframing.

**Comment by DrewBradley** [comment]
![IMG_D59C903E3083-1](https://user-images.githubusercontent.com/64617435/101286394-837cea80-37a7-11eb-849d-9ec7907c1698.jpeg)
![IMG_5673](https://user-images.githubusercontent.com/64617435/101286402-8e377f80-37a7-11eb-8938-9b88390ade56.PNG)

**Comment by dietza** [comment]
![File](https://user-images.githubusercontent.com/64617223/101286793-cfc92a00-37a9-11eb-8987-0a07ca81a326.jpg)
![File (1)](https://user-images.githubusercontent.com/64617223/101286800-d657a180-37a9-11eb-8edc-80fd00c342e0.jpg)
